title: scratch3-if-then-else
hero_image: images/banner.png
description: scratch3-if-then-else description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
