---
title: Defnyddio'r blociau os...yna ac os...yna...fel arall
hero_image: images/banner.png
description: Defnyddio'r blociau os...yna ac os...yna...fel arall
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Defnyddio'r blociau os...yna ac os...yna...fel arall
