---
title: Usando os blocos "se... então" e "se... então... senão"
hero_image: images/banner.png
description: Usando os blocos "se... então" e "se... então... senão"
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Usando os blocos "se... então" e "se... então... senão"
