---
title: Použití bloků když...tak a když...tak...jinak
hero_image: images/banner.png
description: Použití bloků když...tak a když...tak...jinak
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Použití bloků když...tak a když...tak...jinak
