---
title: Usar bloques si...entonces y si...entonces...si no
hero_image: images/banner.png
description: Usar bloques si...entonces y si...entonces...si no
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Usar bloques si...entonces y si...entonces...si no
