---
title: Using if...then and if...then...else blocks
hero_image: images/banner.png
description: Using if...then and if...then...else blocks
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Using if...then and if...then...else blocks
