---
title: Używanie bloków if...then i if...then...else
hero_image: images/banner.png
description: Używanie bloków if...then i if...then...else
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - 
    title: Używanie bloków if...then i if...then...else
