---
title: Używanie bloków "jeżeli...to" i "jeżeli...to...w przeciwnym razie"
hero_image: images/banner.png
description: Używanie bloków "jeżeli...to" i "jeżeli...to...w przeciwnym razie"
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Używanie bloków "jeżeli...to" i "jeżeli...to...w przeciwnym razie"
