---
title: Utiliser des blocs si...alors et si...alors...sinon
hero_image: images/banner.png
description: Utiliser des blocs si...alors et si...alors...sinon
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Utiliser des blocs si...alors et si...alors...sinon
